<?php
$buttonLabel = $block->getButtonLabel();
$messageLabel = $block->getMessageLabel();
?>

<div class="block block-reversio-rma-create-signedinlink">
    <div class="block-title">
        <strong><?php echo __('Returns') ?></strong>
    </div>
    <div class="block-content">
        <div id="reversio-rma-create-signedinlink-label"><?php echo $messageLabel ?></div>
        <?php if ($buttonLabel) : ?>
        <br/>
        <button id="reversio-rma-create-signedinlink-link" class="action primary" type="button"><span><?php echo strtoupper($buttonLabel) ?></span></button>
        <?php endif; ?>
    </div>
</div>

<script type="text/x-magento-init">
{
    "#reversio-rma-create-signedinlink-link": {
        "ReversIo_RMA/js/create-signedinlink": {"callback_url":"<?php echo $block->getUrl('reversio_rma/signedinlink/create', ['order_id' => $block->escapeHtml($block->getOrderId())]) ?>"}
    }
}
</script>
